### ISSUE TITLE
Auto indentation

### ISSUE THREAD

**Issue by ericliddle** [kmsolberg/instanews#2]
Knowing that indentation is something that is so closely watch I'm submitting this as a secondary issue, but it's more of an FYI.  In CSS the formatting needs to be done manually, however, in HTML and you js file, you're able to right click, and auto format.  This has already been taken care of, but it's extremely useful, as well as time saving.

**Comment by rcass** [comment]
Even though there is an auto format, it is highly recommend (esp when learning) to you though this your self. 
Best practice is to maintain proper indentation as you write your code. Be careful on not becoming too reliant on auto formatting. 
Also the HTML indentation looked good to me from the start 👍 

So, really this is a non-issue, so this also can be closed. ✔️
